[package]
name = "alphanumeric-sort"
version = "1.0.6"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/alphanumeric-sort"
homepage = "https://magiclen.org/alphanumeric-sort"
keywords = ["sort", "alphanumeric", "path", "file", "number"]
categories = ["algorithms"]
description= "This crate can help you sort order for files and folders whose names contain numerals."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/alphanumeric-sort"
branch = "master"

[dependencies]
